"""
14-section forensic report generator.
Enforces all 14 mandatory sections. Renders Consultant and Planner views.
Appends recurring pattern and systemic sections when L4 flags are set.
"""
from __future__ import annotations
import logging
from evidence.models import (
    Classification,
    EvidenceGraph,
    ForensicReport,
    InvestigationContext,
    NarrationResult,
)

logger = logging.getLogger(__name__)

_SECTIONS = [
    ("executive_summary",        "1. Executive Summary"),
    ("issue_classification",     "2. Issue Classification"),
    ("affected_system_boundary", "3. Affected System Boundary"),
    ("evidence_timeline",        "4. Evidence Timeline"),
    ("evidence_graph_summary",   "5. Evidence Graph Summary"),
    ("confirmed_findings",       "6. Confirmed Findings"),
    ("probable_root_causes",     "7. Probable Root Causes"),
    ("missing_data_gaps",        "8. Missing Data Gaps"),
    ("recommended_actions",      "9. Recommended Actions"),
    ("sap_objects_to_check",     "10. SAP Objects to Check"),
    ("logs_and_transactions",    "11. Logs and Transactions to Review"),
    ("business_impact",          "12. Business Impact"),
    ("escalation_path",          "13. Escalation Path"),
    ("preventive_recommendation","14. Preventive Recommendation"),
]

_MISSING_PLACEHOLDER = "[MISSING DATA: section could not be generated — manual review required]"


def _build_view(
    sections_data: dict,
    classification: Classification,
    graph: EvidenceGraph,
    ctx: InvestigationContext,
    incident_id: str,
    view_type: str,  # 'consultant' | 'planner'
    pattern_result=None,
) -> str:
    """Render a complete report view with all 14 sections enforced."""
    lines = [
        f"# USCIA Forensic Investigation Report — {view_type.upper()} VIEW",
        f"## Investigation: {ctx.material} / Plant {ctx.plant}",
        f"## Incident Type: {ctx.incident_type}",
        f"## Root Cause: {classification.root_cause} [{classification.confidence} confidence]",
        f"## Incident ID: {incident_id}",
        "---",
    ]

    for key, header in _SECTIONS:
        content = sections_data.get(key, "")
        if not content:
            # Auto-generate minimal content from deterministic data
            content = _auto_section(key, classification, graph, ctx, view_type)
        if not content:
            content = _MISSING_PLACEHOLDER
        lines.append(f"\n## {header}\n\n{content}")

    # Append machine-readable action block (always present)
    lines.append("\n## Recommended Actions (Machine-Readable)\n")
    for action in classification.remediation_actions:
        lines.append(
            f"- action_type: {action.action_type}\n"
            f"  action_params: {action.action_params}\n"
            f"  requires_approval: {action.requires_approval}\n"
            f"  rank: {action.rank}"
        )

    # L4 patterns
    if pattern_result:
        if pattern_result.systemic:
            lines.append(
                f"\n## SYSTEMIC ISSUE DETECTED\n\n"
                f"This root cause ({classification.root_cause}) has occurred "
                f"{pattern_result.occurrence_count} times for material {ctx.material} "
                f"plant {ctx.plant} in the last 90 days. This is classified as a SYSTEMIC ISSUE "
                "requiring a permanent architectural fix, not a one-time remediation."
            )
        elif pattern_result.pattern_flagged:
            lines.append(
                f"\n## RECURRING PATTERN DETECTED\n\n"
                f"This root cause ({classification.root_cause}) has occurred "
                f"{pattern_result.occurrence_count} times for material {ctx.material} "
                f"plant {ctx.plant} in the last 90 days. Recommend systemic review."
            )

    lines.append(f"\n---\n*Report generated by USCIA | Incident ID: {incident_id}*")

    # Machine-readable system status block — three-state: has_data / no_data / missing
    # Systems that only return material-specific data (filtered by material+plant)
    _MATERIAL_SPECIFIC = {
        "S4HANA_PLANNED_ORDER", "S4HANA_MATERIAL_PLANNING", "S4HANA_PIR",
        "S4HANA_PPDS_CONSTRAINTS",
    }
    # When material not found, all S4HANA operational systems show no_data
    material_not_found = classification.root_cause == "MATERIAL_NOT_FOUND"

    def _has_records(node) -> bool:
        if not node.raw_payload:
            return False
        p = node.raw_payload if isinstance(node.raw_payload, dict) else {}
        items = (p.get("value") or p.get("results") or
                 p.get("data") or p.get("SupplyOrders") or [])
        return isinstance(items, list) and len(items) > 0

    def _system_state(node) -> str:
        if node.status != "AVAILABLE":
            return "missing"
        # If material not found, all S4HANA systems that should filter by material show no_data
        if material_not_found and node.system_name.startswith("S4HANA_"):
            return "no_data"
        if _has_records(node):
            return "has_data"
        return "no_data"

    has_data_sys = [n.system_name for n in graph.nodes if _system_state(n) == "has_data"]
    no_data_sys  = [n.system_name for n in graph.nodes if _system_state(n) == "no_data"]
    missing_sys  = [n.system_name for n in graph.nodes if _system_state(n) == "missing"]

    lines.append(
        f"\n<!-- USCIA_SYSTEMS_HAS_DATA: {','.join(has_data_sys)} -->"
        f"\n<!-- USCIA_SYSTEMS_NO_DATA: {','.join(no_data_sys)} -->"
        f"\n<!-- USCIA_SYSTEMS_MISSING: {','.join(missing_sys)} -->"
    )

    return "\n".join(lines)


def _auto_section(
    key: str,
    classification: Classification,
    graph: EvidenceGraph,
    ctx: InvestigationContext,
    view_type: str,
) -> str:
    """Generate deterministic content for sections not filled by LLM.
    Planner view gets concise, action-focused content.
    Consultant view gets technical detail.
    """
    available = [n.system_name for n in graph.nodes if n.status == "AVAILABLE"]
    missing = [n.system_name for n in graph.nodes if n.status == "MISSING_DATA"]
    is_planner = view_type == "planner"

    if key == "executive_summary":
        if is_planner:
            return (
                f"Investigation of material {ctx.material} at plant {ctx.plant}: "
                f"{ctx.incident_type}. "
                f"Root cause: {classification.root_cause} ({classification.confidence} confidence). "
                f"Evidence collected from {len(available)} of 12 systems."
            )
        return (
            f"Investigation of {ctx.incident_type} for material {ctx.material}, plant {ctx.plant}. "
            f"Root cause classified as {classification.root_cause} with {classification.confidence} confidence. "
            f"Evidence retrieved from {len(available)} systems; {len(missing)} systems returned MISSING DATA."
        )

    if key == "issue_classification":
        if is_planner:
            return (
                f"Root Cause: {classification.root_cause} | Confidence: {classification.confidence}\n"
                f"{classification.description}"
            )
        return (
            f"Root Cause: {classification.root_cause}\n"
            f"Confidence: {classification.confidence}\n"
            f"Rule Applied: {classification.rule_id}\n"
            f"Description: {classification.description}"
        )

    if key == "affected_system_boundary":
        if is_planner:
            return (
                f"{len(available)} systems returned data: {', '.join(available)}.\n"
                f"{len(missing)} systems unavailable: {', '.join(missing)}."
            )
        return f"Systems with evidence: {', '.join(available)}\nSystems MISSING DATA: {', '.join(missing)}"

    if key == "confirmed_findings":
        return "\n".join(classification.confirmed_findings) or _MISSING_PLACEHOLDER

    if key == "probable_root_causes":
        return "\n".join(classification.probable_findings) or "No probable findings beyond root cause classification."

    if key == "missing_data_gaps":
        if is_planner:
            gap_systems = [n.system_name for n in graph.nodes if n.status == "MISSING_DATA"
                           and n.system_name not in {"SAP_CPI", "SAP_PIPO", "CLOUD_ALM"}]
            if gap_systems:
                return (
                    f"The following systems could not provide data and require manual investigation: "
                    f"{', '.join(gap_systems)}. "
                    f"IBP supply data is also unavailable — the IBP→S/4HANA integration chain cannot be fully verified."
                )
            return "All critical S/4HANA systems provided data. IBP integration layer requires manual verification."
        return "\n".join(classification.missing_findings) or "No missing data gaps identified."

    if key == "recommended_actions":
        actions = classification.remediation_actions
        if not actions:
            return _MISSING_PLACEHOLDER
        if is_planner:
            lines = []
            for a in actions:
                desc = a.action_params.get("description", a.action_type)
                lines.append(f"[Action {a.rank}] {desc}")
            return "\n".join(lines)
        return "\n".join(
            f"[Rank {a.rank}] {a.action_type} — {a.action_params.get('description', '')} | requires_approval: {a.requires_approval}"
            for a in actions
        )

    if key == "evidence_graph_summary":
        if is_planner:
            if graph.broken_boundaries:
                return (
                    f"The investigation found {len(graph.broken_boundaries)} broken link(s) in the supply chain: "
                    + "; ".join(graph.broken_boundaries[:3])
                )
            return f"Evidence collected from {len(available)} systems. No broken integration boundaries detected in available data."
        return (
            f"Nodes: {len(graph.nodes)} | Links: {len(graph.links)} | "
            f"Broken boundaries: {len(graph.broken_boundaries)}\n"
            + ("\n".join(graph.broken_boundaries) if graph.broken_boundaries else "No broken boundaries detected.")
        )

    return ""


def generate_report(
    narration: NarrationResult,
    classification: Classification,
    graph: EvidenceGraph,
    ctx: InvestigationContext,
    incident_id: str,
    pattern_result=None,
) -> ForensicReport:
    """
    Produce a complete 14-section forensic report in Consultant and Planner views.
    All 14 sections are mandatory — missing sections receive a MISSING_DATA placeholder.
    """
    consultant_view = _build_view(
        narration.consultant_sections, classification, graph, ctx,
        incident_id, "consultant", pattern_result,
    )
    planner_view = _build_view(
        narration.planner_sections, classification, graph, ctx,
        incident_id, "planner", pattern_result,
    )

    # Validate all 14 section headers are present in both views
    for _, header in _SECTIONS:
        if header not in consultant_view:
            consultant_view += f"\n## {header}\n\n{_MISSING_PLACEHOLDER}"
        if header not in planner_view:
            planner_view += f"\n## {header}\n\n{_MISSING_PLACEHOLDER}"

    logger.info(
        "M5.achieved: forensic report delivered — sections=14, root_cause=%s, persisted_incident_id=%s",
        classification.root_cause, incident_id,
    )

    return ForensicReport(
        consultant_view=consultant_view,
        planner_view=planner_view,
        persisted_incident_id=incident_id,
        sections_count=14,
    )
